### ISSUE TITLE
Exercise 20's solution doesn't run

### ISSUE THREAD

**Issue by itsthejazzkid** [jhusain/learnrx#41]
I just reached E.20 and it looks like one of the functions is undefined. (Screenshot is of 'Show Answer' solution)

![screenshot of attempt to run solution](https://cloud.githubusercontent.com/assets/3161613/5329589/62891ad6-7d6a-11e4-9116-7d1b6024483b.png)

**Comment by Kliriklara** [comment]
The "undefined is not a function" error occurs because the concatMap and concatAll method are indeed not defined. 

You can either run E.10 and then E.13, so that the code blocks containing the implementation of concatMap and concatAll get executed. Or you can add the two methods to the Array's prototype on top of the E.20 exercise.

**Comment by bloodyKnuckles** [comment]
I ran into the same problem. My error was more specific, telling me that `movieLists.concatMap` was not a defined function. So I tried re-running E.13, and that gave me the error that `concatAll` was not a function, so I re-ran E.10, then re-re-ran E.13, then E.20 ran fine.

The problem then is, why are we loosing those implementations when closing the page or turning off the computer and coming back to it?
